name: Comment on Issue

on:
  issues:
    types:
      - opened

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Add a comment to the issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMENT="Thank you for opening this issue! We will look into it."
          echo "Commenting on issue ${{ github.event.issue.number }}"
          curl -X POST "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            -d "{\"body\": \"$COMMENT\"}"
