name: issue created

on:
  issues:
    types: [opened]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
      - name: "dump github context"
        run: echo '${{ toJSON(github.event) }}' | jq
  comment-with-api:
     runs-on: ubuntu-latest
     steps:
       - name: create comment with api
         run: |
           gh  api -X POST \
             http://api.github.com/repo/${ORGANISATION}/${REPOSITORY}/issues/${ISSUE_NUMBER}/comments\
             -f body='
             comment from api
             '
           env:
             GITHUB_TOKEN:${{secrets.GITHUB_TOKEN}}
             ORGANISATION:${{github.event.organisation.login}}
             REPOSITORY:${{github.event.repository.name}}
             ISSUE_NUMBER:${{github.event.issue.number}}
       
